server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/microDB
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/microservices-realm
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
